env_id: Hopper-v4
env:
  parameter: friction
  drift_type: linear
  magnitude: 0.27
  period: 15000
  base_value: 0.9
  bounds:
  - 0.54
  - 1.26
wandb:
  project: att_3_Hopper_Moderate_Comparison
  tags:
  - hopper
  - moderate
  - ppo
  - friction
  - linear
  - nsmdmpi
  - tuned
  mode: online
train:
  algorithm: PPO
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  total_timesteps: 1000000
  seed: 42
nsmdmpi:
  enabled: true
  V_R: 12.278003224918699
  V_P: 8.447093807430807
  V_pi_star: 2.7492641675302627
  kappa_base: 0.205722634466976
  lambda_base: 1.4124842855984459
  kappa_adaptive: true
  lambda_adaptive: true
  sensitivity: 0.1
  trust_region_sensitivity: 5.060509071764029
  regularization_sensitivity: 1.112520471983751
  max_ent_coef: 0.09002052320815648
  drift_window_size: 900
paths:
  log_dir: logs/
  model_dir: models/
  video_dir: videos/
