env_id: LunarLander-v3
env:
  parameter: wind_power
  drift_type: linear
  magnitude: 0.3
  period: 15000
  base_value: 0.0
wandb:
  project: att_3_LunarLander_Moderate_Comparison
  tags:
  - lunarlander
  - moderate
  - ppo
  - wind_power
  - linear
  - baseline
  mode: online
train:
  algorithm: PPO
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  total_timesteps: 1000000
  seed: 42
nsmdmpi:
  enabled: false
paths:
  log_dir: logs/
  model_dir: models/
  video_dir: videos/
