wandb_version: 1

V_P:
  value: 31.542030815901715
V_R:
  value: 32.18689733157058
V_pi_star:
  value: 16.235117116642524
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 259
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.28767882741940676
lambda_base:
  value: 1.5893193048822971
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.11300977301715484
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.4675989464621955
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 17.14952235346488
