wandb_version: 1

V_P:
  value: 27.806668078842375
V_R:
  value: 37.003651829569506
V_pi_star:
  value: 19.870316618745026
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 357
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.267450144961417
lambda_base:
  value: 2.3547089190574764
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.054726934744281086
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.901646010435984
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 15.119544031190276
