wandb_version: 1

V_P:
  value: 46.31792930696007
V_R:
  value: 47.592362947644375
V_pi_star:
  value: 10.848629400999949
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 966
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2996616353390622
lambda_base:
  value: 4.478885645911888
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.16638856408539912
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 8.819384326335177
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.0641856168560295
