wandb_version: 1

V_P:
  value: 27.49775876546826
V_R:
  value: 41.99322971560771
V_pi_star:
  value: 11.342205570078814
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 319
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.19076195042997557
lambda_base:
  value: 1.207728203816484
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.17017237840815524
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.5904801627776997
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 13.016518331202516
