wandb_version: 1

V_P:
  value: 28.22750017809952
V_R:
  value: 29.835853398064963
V_pi_star:
  value: 24.404242330733112
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 396
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.1900951109140341
lambda_base:
  value: 1.008869998459199
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.18650478509208104
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.96427956668553
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.491653139143828
