wandb_version: 1

V_P:
  value: 28.90927035196833
V_R:
  value: 42.73668883671428
V_pi_star:
  value: 14.343889491550916
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 307
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.25681339196858083
lambda_base:
  value: 1.100614788793219
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.18661037402554223
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.714068108152871
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 16.089702478112322
