wandb_version: 1

V_P:
  value: 24.619098607761508
V_R:
  value: 42.01748865502136
V_pi_star:
  value: 13.783348299740029
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 340
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.23434785231906163
lambda_base:
  value: 3.4336235999424307
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.17829207190121943
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.783240170990719
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.45602360555832
