wandb_version: 1

V_P:
  value: 25.594795883135863
V_R:
  value: 41.06348364279611
V_pi_star:
  value: 15.13853466160479
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 371
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2939848746047704
lambda_base:
  value: 3.012564680140555
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.17346893020393844
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.8277982959522503
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 14.81206655987029
