wandb_version: 1

V_P:
  value: 33.920570114877336
V_R:
  value: 34.35728925908802
V_pi_star:
  value: 20.420847674245216
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 221
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.26666667706401515
lambda_base:
  value: 1.2935401439240954
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.11802588783063986
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.66780492179012
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 13.84207786503186
