wandb_version: 1

V_P:
  value: 28.52681957841038
V_R:
  value: 29.946674660485815
V_pi_star:
  value: 16.133389403338676
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 729
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.35195013346885273
lambda_base:
  value: 1.284284903883227
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.10859231279965748
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.755252702786947
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.841460675817459
