wandb_version: 1

V_P:
  value: 30.63934522189603
V_R:
  value: 37.78395083877177
V_pi_star:
  value: 12.889556608726618
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 393
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.212583532863212
lambda_base:
  value: 1.062283061068192
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1701084973872513
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.198249586834809
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 14.842253839430516
