wandb_version: 1

V_P:
  value: 23.495435634086185
V_R:
  value: 39.58999174472403
V_pi_star:
  value: 15.381479991124252
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 237
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.28466402049692147
lambda_base:
  value: 2.478757734848138
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.13277845815796338
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.0178417445846204
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 17.015148205664502
