wandb_version: 1

V_P:
  value: 35.70438145464643
V_R:
  value: 40.87817326336968
V_pi_star:
  value: 16.344775183393697
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 256
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2909789255103998
lambda_base:
  value: 1.7497598776444008
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.12221577760233744
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.792497306296317
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.465269993710173
