wandb_version: 1

V_P:
  value: 19.070681978564576
V_R:
  value: 16.96427713059348
V_pi_star:
  value: 7.4105196767487245
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1461
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.21271333653683877
lambda_base:
  value: 1.8626608125689432
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.03215279355591669
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.5644026532820976
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 5.897013308800415
