wandb_version: 1

V_P:
  value: 18.094998136658347
V_R:
  value: 18.346129023863732
V_pi_star:
  value: 4.495469951328997
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1153
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.25407559005610925
lambda_base:
  value: 1.7242571973147802
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.021079454196546055
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.8216221832283876
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.233293745074691
