wandb_version: 1

V_P:
  value: 18.881373528288293
V_R:
  value: 18.255726453503144
V_pi_star:
  value: 8.371545216425323
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1889
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.25898994784233487
lambda_base:
  value: 1.6304754428130237
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0508011379083606
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.3585260751696393
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 6.555298193783138
