wandb_version: 1

V_P:
  value: 17.31779129328372
V_R:
  value: 17.55248583454555
V_pi_star:
  value: 4.453796904658047
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1550
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.23478339669375511
lambda_base:
  value: 1.8620503102767896
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.01304657176249554
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.905766301359331
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.6980754828555105
