wandb_version: 1

V_P:
  value: 15.456656287329924
V_R:
  value: 13.993875827695232
V_pi_star:
  value: 7.421105017418376
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1227
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2612709712104764
lambda_base:
  value: 1.82155123527537
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0778096296033183
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.3606065575608075
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.786220190306717
