wandb_version: 1

V_P:
  value: 18.440426838434224
V_R:
  value: 16.868441179428974
V_pi_star:
  value: 2.732856520563311
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1287
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2573115546174205
lambda_base:
  value: 1.7062868042393164
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.013668323863419712
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.105470680209117
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.522558564034018
