wandb_version: 1

V_P:
  value: 15.848769654054848
V_R:
  value: 18.917196113809727
V_pi_star:
  value: 7.464767397640776
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1348
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2212942877717958
lambda_base:
  value: 1.8067161319989449
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.03523185480234775
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.8064579057870496
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.725039563421456
