wandb_version: 1

V_P:
  value: 18.863613434594132
V_R:
  value: 18.635009993658834
V_pi_star:
  value: 5.190984652228296
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1804
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.25024926249217483
lambda_base:
  value: 1.8203454816326077
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.04185225307214227
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.9164664807494265
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.881104883809789
