wandb_version: 1

V_P:
  value: 15.798793570279193
V_R:
  value: 15.27204786680012
V_pi_star:
  value: 5.11795122212154
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1777
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2287830937505765
lambda_base:
  value: 1.7214135232050725
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.01653323976349601
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.7397054791338693
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 6.860669691168443
