wandb_version: 1

V_P:
  value: 40.88765209766497
V_R:
  value: 25.96499801198121
V_pi_star:
  value: 23.440992250349844
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 850
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.272285682340936
lambda_base:
  value: 1.2245279359082604
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1650911127160215
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.238479128992067
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 14.272652170428309
