wandb_version: 1

V_P:
  value: 48.93461572639504
V_R:
  value: 22.885169054945425
V_pi_star:
  value: 23.74026182405929
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 708
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3142393051456147
lambda_base:
  value: 1.2697793938659054
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.10715711797260773
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.975338021648675
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 16.096186729590954
