wandb_version: 1

V_P:
  value: 36.57876086088726
V_R:
  value: 28.137718775196692
V_pi_star:
  value: 13.534000832252412
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 270
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.22810218841503477
lambda_base:
  value: 4.772230566932775
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.18179089124288855
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.074968547644325
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 15.48672858538274
