wandb_version: 1

V_P:
  value: 41.84057114204615
V_R:
  value: 20.266973704157778
V_pi_star:
  value: 24.123924743229125
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 934
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.30223158984404186
lambda_base:
  value: 2.2461513870172847
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.10921138843389992
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 6.122532714711429
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 14.64567123244952
