wandb_version: 1

V_P:
  value: 41.5121995416993
V_R:
  value: 30.86387694089174
V_pi_star:
  value: 23.75894462930345
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 992
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3043781324963627
lambda_base:
  value: 3.884028541172507
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.13632093899097514
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 6.964082161978114
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.38321852840211
