wandb_version: 1

V_P:
  value: 27.382189357284297
V_R:
  value: 31.56069174329872
V_pi_star:
  value: 24.666526985644825
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 523
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.30467549972354524
lambda_base:
  value: 2.862006311093941
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.16093842437029238
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.555375234699187
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 5.3040357165720735
