wandb_version: 1

V_P:
  value: 43.2544304124452
V_R:
  value: 26.070677085620673
V_pi_star:
  value: 18.83644387245436
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 940
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3331968030564283
lambda_base:
  value: 1.2046648817560133
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1188389475395599
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.567953710198491
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 11.677679297887366
