wandb_version: 1

V_P:
  value: 45.226367239503176
V_R:
  value: 27.961268691160555
V_pi_star:
  value: 19.25183913666246
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 983
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.34442057328034953
lambda_base:
  value: 1.9239992427829593
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.13994488739960312
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.4034877540349395
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 16.29272924379955
