wandb_version: 1

V_P:
  value: 35.97341027819526
V_R:
  value: 25.184332001973793
V_pi_star:
  value: 22.3797855876234
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 754
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.22416596533533992
lambda_base:
  value: 1.6302942813022967
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09372610209702352
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.676356257603853
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 17.427703397505084
