wandb_version: 1

V_P:
  value: 43.674889902731145
V_R:
  value: 30.328291939140858
V_pi_star:
  value: 22.54707976038369
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 618
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2124926135748446
lambda_base:
  value: 1.9584094096177007
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.138154047810355
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 8.708442070226244
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.70885937739204
