wandb_version: 1

V_P:
  value: 26.81434747736667
V_R:
  value: 41.192389136043
V_pi_star:
  value: 24.62065851436045
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 699
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.23832796948834875
lambda_base:
  value: 2.7088286386661156
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.10744969103095728
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.077103124974178
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.29874284785007
