wandb_version: 1

V_P:
  value: 42.23443180228341
V_R:
  value: 25.628056583877125
V_pi_star:
  value: 23.534109773094613
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 727
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.20295251862308877
lambda_base:
  value: 1.9416498018567376
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09409287709664854
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.254460264106765
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.39197521326117
