wandb_version: 1

V_P:
  value: 34.23963201574641
V_R:
  value: 34.894924414321736
V_pi_star:
  value: 23.852620804800047
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 600
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.23916871688583452
lambda_base:
  value: 2.3395647085950793
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1004786481218992
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.27339601291127
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 15.312291394201644
