wandb_version: 1

V_P:
  value: 31.53652066786548
V_R:
  value: 37.11301579127572
V_pi_star:
  value: 20.491320134340995
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 607
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.20310202438656472
lambda_base:
  value: 1.406846219465956
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.17148727714191708
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.7452443732476945
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.690123415343983
