wandb_version: 1

V_P:
  value: 35.463916093767125
V_R:
  value: 28.822790671727528
V_pi_star:
  value: 22.598325693350876
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 732
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2253727418079692
lambda_base:
  value: 2.4969775170823167
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1617225367052359
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.981932861421528
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.482802438827623
