wandb_version: 1

V_P:
  value: 35.48939496945401
V_R:
  value: 27.18365173521903
V_pi_star:
  value: 23.593446618466928
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 550
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2500643384459909
lambda_base:
  value: 1.160923216839706
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.16274432803664785
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.974521814863875
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.008072744642952
