wandb_version: 1

V_P:
  value: 41.194537858244985
V_R:
  value: 43.596577558454854
V_pi_star:
  value: 22.590947634204262
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 805
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.15416027953616315
lambda_base:
  value: 1.7850388028682205
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0882096589556765
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.694222285669756
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.56364431165515
