wandb_version: 1

V_P:
  value: 34.93587438142872
V_R:
  value: 42.90340360029748
V_pi_star:
  value: 22.76729793248893
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 899
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.17475337707892313
lambda_base:
  value: 1.4181778771067235
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.10436705146983048
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.424203999950352
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.79308433206818
