wandb_version: 1

V_P:
  value: 25.990428589578062
V_R:
  value: 43.61159606040847
V_pi_star:
  value: 24.0998385178305
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 287
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.19179723801527093
lambda_base:
  value: 1.8113025830479923
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08351455303638858
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.124412971458668
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 17.897532967257565
