wandb_version: 1

V_P:
  value: 40.04900222878779
V_R:
  value: 35.068048139979574
V_pi_star:
  value: 24.55941304230017
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 605
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.21053479236629155
lambda_base:
  value: 2.417951821828893
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1513059098371573
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.382519147042457
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.635870927049428
