wandb_version: 1

V_P:
  value: 32.862936568416075
V_R:
  value: 26.75755214243625
V_pi_star:
  value: 24.502923722227617
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 420
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.31675986842452086
lambda_base:
  value: 1.2099777381652204
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1798187479800798
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.17158485396332
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 16.19789727506854
