wandb_version: 1

V_P:
  value: 43.90886975286598
V_R:
  value: 34.831381258764
V_pi_star:
  value: 21.424922276835833
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 531
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.28461287219747
lambda_base:
  value: 2.005668208567343
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0989301147978386
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 8.00749161485556
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 16.432741770675428
