wandb_version: 1

V_P:
  value: 35.45878899846077
V_R:
  value: 33.09458730685559
V_pi_star:
  value: 17.311880745489926
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 767
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.18692649624112792
lambda_base:
  value: 2.509888419124603
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.06761135058662489
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.05053190608166
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.651908874788518
