wandb_version: 1

V_P:
  value: 22.120602226972537
V_R:
  value: 49.20375226090049
V_pi_star:
  value: 22.354315104930627
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 644
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.1838872221545851
lambda_base:
  value: 2.237148434144987
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09990678445081944
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.500259832597015
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 11.49714021527145
