wandb_version: 1

V_P:
  value: 27.35847726468829
V_R:
  value: 48.32174799943576
V_pi_star:
  value: 22.19626399075669
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 620
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.15307692113535326
lambda_base:
  value: 1.3481234717018171
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09456313495811886
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.158282077950282
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.993585213878593
