wandb_version: 1

V_P:
  value: 30.7347748261074
V_R:
  value: 35.73348847971791
V_pi_star:
  value: 22.976478348825744
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 711
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.22560416164983504
lambda_base:
  value: 1.2896615119688617
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08297036540810462
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.124639819984646
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.16183171123371
