wandb_version: 1

V_P:
  value: 16.22773726282961
V_R:
  value: 6.292787472887431
V_pi_star:
  value: 8.463625484763591
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 787
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.19959132107967076
lambda_base:
  value: 1.7534015772817193
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.021249936529411248
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.6477346781116258
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 2.344246918954693
