wandb_version: 1

V_P:
  value: 17.72315032190567
V_R:
  value: 7.322526812566073
V_pi_star:
  value: 9.080325784805892
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1851
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.26340109288155267
lambda_base:
  value: 1.7211296983579614
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0629908286607846
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.4559593317748725
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 4.662784426050972
