wandb_version: 1

V_P:
  value: 19.670061711087666
V_R:
  value: 18.817102294215232
V_pi_star:
  value: 9.078396930899668
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 728
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.11572841505535232
lambda_base:
  value: 1.6979088759066732
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.06854398354552059
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.7467535534975127
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.47673722180022
