wandb_version: 1

V_P:
  value: 16.217076605642717
V_R:
  value: 17.987914372745784
V_pi_star:
  value: 9.980772123779689
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 594
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10019026822323952
lambda_base:
  value: 1.6274488414780386
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.06187167286162954
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.396789110348635
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.985259182486239
