wandb_version: 1

V_P:
  value: 19.332449094666977
V_R:
  value: 16.585990656241595
V_pi_star:
  value: 9.38968208441683
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1097
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10814682381270868
lambda_base:
  value: 1.2195956255124545
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08414338727940386
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.074239764824221
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.66885286552761
