wandb_version: 1

V_P:
  value: 16.887576909802412
V_R:
  value: 12.497225012965806
V_pi_star:
  value: 8.371710564283998
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 670
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.137417933554143
lambda_base:
  value: 1.7800799736887685
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.05091307226550368
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.920993357101917
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.77758801643694
