wandb_version: 1

V_P:
  value: 16.683718037021634
V_R:
  value: 19.509949220143337
V_pi_star:
  value: 8.072716175247379
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1153
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10547295489054526
lambda_base:
  value: 0.6510758231978494
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08252854756503888
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.953945207017946
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 5.289376827891737
