wandb_version: 1

V_P:
  value: 18.29645200386968
V_R:
  value: 18.659178425694662
V_pi_star:
  value: 9.137480323083132
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1314
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.19166371466133095
lambda_base:
  value: 0.6123031680964233
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.03163996378848159
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.779399136660783
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 6.3757579362785
