wandb_version: 1

V_P:
  value: 18.875495048791
V_R:
  value: 9.723806549969558
V_pi_star:
  value: 7.9657127486912
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 537
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10431966614135536
lambda_base:
  value: 0.852307245239257
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.02021392556755746
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.267270082060586
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.898927383435366
