wandb_version: 1

V_P:
  value: 11.39506189695575
V_R:
  value: 16.02225397191539
V_pi_star:
  value: 5.506862132683581
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 824
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.20337334028511264
lambda_base:
  value: 0.5403898066587981
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.07585642938828115
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.7882262857179496
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.8773543397164705
