wandb_version: 1

V_P:
  value: 18.448178776968483
V_R:
  value: 16.080343113528194
V_pi_star:
  value: 9.516660662888604
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 959
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.1950926653579606
lambda_base:
  value: 0.966611155656619
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.01792857230781275
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.289646248839601
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.2960028004517
