wandb_version: 1

V_P:
  value: 19.71782711430525
V_R:
  value: 18.705564127798297
V_pi_star:
  value: 8.383622863759275
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 664
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.18352174630679885
lambda_base:
  value: 1.442297435960992
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.099149336205259
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.80750273613635
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 6.198444188963705
