wandb_version: 1

V_P:
  value: 18.70815130367047
V_R:
  value: 15.142213072392966
V_pi_star:
  value: 7.585979505250848
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 620
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.13655794094878343
lambda_base:
  value: 1.0611830922445886
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.03716428019057072
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.299941095334042
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.092447420664516
