wandb_version: 1

V_P:
  value: 6.044640159825554
V_R:
  value: 19.90660946357511
V_pi_star:
  value: 3.760360556754005
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 644
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.18911840757865697
lambda_base:
  value: 1.967993889021168
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.01872336798939199
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.9426413657031643
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.588403547238869
