wandb_version: 1

V_P:
  value: 18.811996617645377
V_R:
  value: 18.598871575971295
V_pi_star:
  value: 9.280502771508232
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1084
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10068641543231738
lambda_base:
  value: 0.9671974813720104
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.03331895876825707
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.67180856383201
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.31214968209677
