wandb_version: 1

V_P:
  value: 18.739309830196145
V_R:
  value: 13.485976043373304
V_pi_star:
  value: 8.56662917774323
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1667
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10186237460302904
lambda_base:
  value: 0.8354577831678505
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.07102183267813592
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.7113657766476624
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.746641961406244
