env_id: LunarLander-v3
env:
- parameter: gravity
  drift_type: sine
  magnitude: 3.0
  period: 8000
  base_value: -10.0
  bounds:
  - -11.9
  - -6.0
- parameter: wind_power
  drift_type: linear
  magnitude: 2.0
  period: 10000
  base_value: 0.0
  bounds:
  - -5.0
  - 5.0
wandb:
  project: att_19_LunarLander
  tags:
  - lunarlander
  - multi-param
  - ppo
  - gravity+wind_power
  - baseline
  mode: online
train:
  algorithm: PPO
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  total_timesteps: 1000000
  seed: 42
nsmdmpi:
  enabled: false
paths:
  log_dir: logs/
  model_dir: models/
  video_dir: videos/
