wandb_version: 1

V_P:
  value: 39.528580785817525
V_R:
  value: 46.60040174245954
V_pi_star:
  value: 16.550664558383296
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 831
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3618669274761698
lambda_base:
  value: 1.7715426341125946
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.17238379386017796
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 8.296123440231439
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 16.521092477769088
