wandb_version: 1

V_P:
  value: 48.61556855841215
V_R:
  value: 43.817237877175224
V_pi_star:
  value: 14.061614366783049
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 982
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2851327122211641
lambda_base:
  value: 2.0792165761656496
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.10107058891336795
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.031599141124138
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.04429181571738
