wandb_version: 1

V_P:
  value: 29.541493448371114
V_R:
  value: 33.776597025875205
V_pi_star:
  value: 24.493926730447654
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 690
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2168199707071348
lambda_base:
  value: 3.7800599021990617
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.16783245015525844
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.668844956695255
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 10.29984279889258
