wandb_version: 1

V_P:
  value: 34.61626494128862
V_R:
  value: 33.758123941452496
V_pi_star:
  value: 24.97719402972134
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 803
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.18011097347334296
lambda_base:
  value: 3.0752974359159584
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.18858013364171167
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.756900730206849
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.75759979682751
