wandb_version: 1

V_P:
  value: 35.82180833121711
V_R:
  value: 20.051390414909186
V_pi_star:
  value: 24.918715481386876
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 883
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.16742708825801472
lambda_base:
  value: 3.366295658822969
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1937899210122509
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.199439248464646
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.418046624485862
