wandb_version: 1

V_P:
  value: 31.86699706726843
V_R:
  value: 33.301320497982516
V_pi_star:
  value: 22.41953361062873
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 756
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.17881300686476342
lambda_base:
  value: 2.1270008914899363
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.17523730887496458
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.012864737578305
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.293712049163576
