wandb_version: 1

V_P:
  value: 33.424313360418864
V_R:
  value: 49.74072623417936
V_pi_star:
  value: 20.59979491518397
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 955
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2961076573566123
lambda_base:
  value: 1.043412830522194
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.11064215233579144
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.44485435852588
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 14.461932060311332
