wandb_version: 1

V_P:
  value: 28.04587677338303
V_R:
  value: 41.29495330809747
V_pi_star:
  value: 22.447770085840983
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 667
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3941923889718735
lambda_base:
  value: 2.522765222026293
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.15275572472832366
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 6.444331171993728
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 15.988725168884429
