wandb_version: 1

V_P:
  value: 38.02010648088293
V_R:
  value: 44.73351575692065
V_pi_star:
  value: 20.92061814279836
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 803
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3410050989107205
lambda_base:
  value: 1.6255346206826309
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1285920286179072
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.46097543500332
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 15.304805584731072
