wandb_version: 1

V_P:
  value: 45.16140423359815
V_R:
  value: 27.11527352561399
V_pi_star:
  value: 20.991348782468627
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 588
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3241151923053278
lambda_base:
  value: 1.9789737187860332
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.15381011441985204
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.92630072088592
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.518068274512867
