wandb_version: 1

V_P:
  value: 34.336047100575605
V_R:
  value: 21.82864621011832
V_pi_star:
  value: 22.464981103572537
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 917
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.31055946208399876
lambda_base:
  value: 3.980234434378664
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.051110837720037786
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.019081672023757
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 15.968742961322032
