wandb_version: 1

V_P:
  value: 48.98927048531496
V_R:
  value: 46.430401547607346
V_pi_star:
  value: 23.292167196991777
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 687
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.37145296811727246
lambda_base:
  value: 3.5190059083898753
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.10242824178176356
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.484424931577198
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 16.429047309559103
