wandb_version: 1

V_P:
  value: 21.479567774593264
V_R:
  value: 45.664098146362946
V_pi_star:
  value: 19.108562522311693
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 811
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.24105209362543356
lambda_base:
  value: 1.9467152388523872
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.06715341138807022
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 9.554510670765108
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.955571894481272
