wandb_version: 1

V_P:
  value: 49.68425295915206
V_R:
  value: 33.34867153760512
V_pi_star:
  value: 24.295015993385093
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 549
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2858456218460591
lambda_base:
  value: 1.861617392299146
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.18220713460102317
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.3975133668168915
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.917847708428383
