wandb_version: 1

V_P:
  value: 43.45213332016773
V_R:
  value: 47.09003506576911
V_pi_star:
  value: 21.46249536671032
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 678
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.34231508015284307
lambda_base:
  value: 1.5902614470726024
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.1175869970237452
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 6.007390299488757
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 12.758377108981822
