wandb_version: 1

V_P:
  value: 37.628034851282635
V_R:
  value: 44.152328164214055
V_pi_star:
  value: 20.604188837567868
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 806
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.26281881950006036
lambda_base:
  value: 1.947649231484501
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.12784986070723164
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.0482654792021493
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 18.171744217036355
