wandb_version: 1

V_P:
  value: 47.26478151392966
V_R:
  value: 39.056190667006405
V_pi_star:
  value: 24.921475300817463
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 586
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.3670964502672539
lambda_base:
  value: 2.3400332118618845
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.14854950769254943
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 8.473239272551641
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 19.857772673086913
