wandb_version: 1

V_P:
  value: 42.07446701072556
V_R:
  value: 38.35918434515119
V_pi_star:
  value: 22.36242846448837
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 271
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2503244853936185
lambda_base:
  value: 3.3019418321641933
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.059769239019821854
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 7.871098697844001
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 15.58437977251082
