wandb_version: 1

V_P:
  value: 40.09560417221511
V_R:
  value: 43.69768045746312
V_pi_star:
  value: 11.07871656885358
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 519
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.16637972227187053
lambda_base:
  value: 2.6201383226693027
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.16489234979599687
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 5.4707222332208865
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.425747985092407
