_wandb:
    value:
        cli_version: 0.23.1
        e:
            1j05ctdvboq5pb2guxwberfxd1zqdugi:
                args:
                    - --create-sweep
                    - --type
                    - extreme
                    - --env
                    - HalfCheetah-v4
                    - --count
                    - "50"
                codePath: scripts/wandb_sweep_agent.py
                codePathLocal: scripts/wandb_sweep_agent.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1003622154240"
                        used: "939073765376"
                email: hungtranbg1704@gmail.com
                executable: /home/hungchan/miniconda3/envs/rl_hf_course/bin/python
                git:
                    commit: 04f7a9e59f2f4c7379079a6c7615d61e7002b5b3
                    remote: https://github.com/hungtrab/NS_MD_MPI.git
                gpu: NVIDIA RTX A2000 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "4294967296"
                      name: NVIDIA RTX A2000 Laptop GPU
                      uuid: GPU-595a2840-bd6f-6c35-c843-4d1510794d22
                host: hungchan-Precision-7560
                memory:
                    total: "32812343296"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /home/hungchan/Work/Deep-RL/scripts/wandb_sweep_agent.py
                python: CPython 3.10.18
                root: /home/hungchan/Work/Deep-RL
                startedAt: "2026-01-18T19:25:15.359633Z"
                writerId: 1j05ctdvboq5pb2guxwberfxd1zqdugi
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 14
            "4": 3.10.18
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
V_P:
    value: 22.26137266679042
V_R:
    value: 25.02380962528543
V_pi_star:
    value: 21.095363116670075
batch_size:
    value: 64
drift_base_value:
    value: 0.9
drift_magnitude:
    value: 0.27
drift_parameter:
    value: friction
drift_period:
    value: 10000
drift_type:
    value: sine
drift_window_size:
    value: 824
env_id:
    value: HalfCheetah-v4
gamma:
    value: 0.99
kappa_base:
    value: 0.22684569440605096
lambda_base:
    value: 4.329565356522757
learning_rate:
    value: 0.0003
max_ent_coef:
    value: 0.16535306160086946
n_envs:
    value: 4
n_steps:
    value: 2048
regularization_sensitivity:
    value: 5.401355682659019
seed:
    value: 42
total_timesteps:
    value: 200000
trust_region_sensitivity:
    value: 11.419964216981445
