env_id: LunarLander-v3
wandb:
  project: att_3_LunarLander_Moderate_Comparison
  tags:
  - lunarlander
  - vanilla
  - ppo
  - no_drift
  mode: online
train:
  algorithm: PPO
  learning_rate: 0.0003
  n_steps: 2048
  batch_size: 64
  gamma: 0.99
  total_timesteps: 500000
  seed: 42
paths:
  log_dir: logs/
  model_dir: models/
  video_dir: videos/
