wandb_version: 1

V_P:
  value: 18.73987868053941
V_R:
  value: 19.95450567901432
V_pi_star:
  value: 9.918130258234289
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 856
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.12627818793990644
lambda_base:
  value: 0.6422753442093065
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08368595410363076
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.705465482069345
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.53543926618718
