wandb_version: 1

V_P:
  value: 19.216410947105015
V_R:
  value: 19.91707832485556
V_pi_star:
  value: 8.994891282755496
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 601
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.25712466828932373
lambda_base:
  value: 0.5320109281056665
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.03165317228582581
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.0856570555638396
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.521668633262747
