wandb_version: 1

V_P:
  value: 15.5769628859916
V_R:
  value: 16.00720285043578
V_pi_star:
  value: 3.851207373516753
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1666
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.27259405265908854
lambda_base:
  value: 0.9384145313345796
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0717819082234407
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.5197562942023954
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 6.750575721668452
