wandb_version: 1

V_P:
  value: 16.61067327398279
V_R:
  value: 17.9830646056163
V_pi_star:
  value: 9.65338720042269
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1096
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.28731247084439593
lambda_base:
  value: 1.6945679891911625
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09560244852050656
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.30822917427068
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.4287878338206195
