wandb_version: 1

V_P:
  value: 18.74940383242354
V_R:
  value: 19.546533388256016
V_pi_star:
  value: 9.227664827066436
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1834
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2497190083301715
lambda_base:
  value: 1.9343841318172736
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.018173295792497372
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.726238393815269
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 3.5359193651307157
