wandb_version: 1

V_P:
  value: 17.047825567032774
V_R:
  value: 16.316260380149107
V_pi_star:
  value: 5.714759623510936
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 646
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.29974317161441955
lambda_base:
  value: 1.5678230426713031
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09484529094504791
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.954433224350656
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.783783301730692
