wandb_version: 1

V_P:
  value: 19.50547824543635
V_R:
  value: 10.499219421452729
V_pi_star:
  value: 8.795731446097031
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1170
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2813189572429813
lambda_base:
  value: 0.9932696596307948
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0797308587541223
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.176957200717582
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.771372432623084
