wandb_version: 1

V_P:
  value: 17.780679673611036
V_R:
  value: 16.57047480136629
V_pi_star:
  value: 9.739328569140511
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1315
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.21861158041851647
lambda_base:
  value: 0.5465185529821308
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.043076127089509655
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.066013888437048
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.926095028094313
