wandb_version: 1

V_P:
  value: 19.733596246191617
V_R:
  value: 13.99444972493944
V_pi_star:
  value: 8.507821891432272
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1979
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.14337910689140854
lambda_base:
  value: 0.8075567480816342
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08596942885238733
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.8035327501894862
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.685267658651584
