wandb_version: 1

V_P:
  value: 16.36402859967601
V_R:
  value: 11.262006979970456
V_pi_star:
  value: 9.991602389692474
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1574
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10444752143937264
lambda_base:
  value: 0.6720750805254994
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08439306381262977
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.837010938801685
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.76858986807682
