wandb_version: 1

V_P:
  value: 17.563203551865065
V_R:
  value: 16.55226607914412
V_pi_star:
  value: 8.958986318281394
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1645
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10263006053899
lambda_base:
  value: 1.8819276890508525
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.011529588484151454
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.390088055812338
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.085984077580308
