wandb_version: 1

V_P:
  value: 19.4799178862892
V_R:
  value: 19.68695902170116
V_pi_star:
  value: 8.069324328404482
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1489
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.22957621573167164
lambda_base:
  value: 0.6021254932469419
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09186433798017228
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.6226186419394417
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.976542299629607
