wandb_version: 1

V_P:
  value: 13.74488296422806
V_R:
  value: 16.020760468226428
V_pi_star:
  value: 3.5859882591240297
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1686
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2898732135078727
lambda_base:
  value: 0.846657285818052
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.07890434164758844
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.1110924030322487
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 5.353507138436449
