wandb_version: 1

V_P:
  value: 18.799301663061776
V_R:
  value: 18.10392516088375
V_pi_star:
  value: 9.533139266466453
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1611
env_id:
  value: Hopper-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2838177206624688
lambda_base:
  value: 0.6832550580244547
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.06910310469713653
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.6858468745879307
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.083550391711752
