wandb_version: 1

V_P:
  value: 11.40512082526461
V_R:
  value: 7.611422044677561
V_pi_star:
  value: 8.817846863066988
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 977
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.17231572151558813
lambda_base:
  value: 0.7160312407374385
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.02893069732614665
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.677218998166849
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.960067834074695
