wandb_version: 1

V_P:
  value: 19.898933543730028
V_R:
  value: 19.32694270576427
V_pi_star:
  value: 7.673572820750395
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1779
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2725607934566131
lambda_base:
  value: 0.8314779008755515
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.06076000105332429
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.0425798315389097
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.74056849418918
