wandb_version: 1

V_P:
  value: 19.402709547799628
V_R:
  value: 17.824787564462795
V_pi_star:
  value: 9.74841867954166
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1631
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.14258674912343103
lambda_base:
  value: 0.5187482416094062
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.06644119045682256
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.713365224210274
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.886864902731542
