wandb_version: 1

V_P:
  value: 19.88444358549676
V_R:
  value: 17.77861621632165
V_pi_star:
  value: 8.6296213320823
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1793
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.21622314274802723
lambda_base:
  value: 0.7292041924621079
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.09258014659305376
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.388431214949266
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.696996868533866
