wandb_version: 1

V_P:
  value: 19.593818448825346
V_R:
  value: 18.60677162493314
V_pi_star:
  value: 7.793559844928977
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1272
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.10567849110066135
lambda_base:
  value: 0.5040050505207155
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08455567380038569
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.734654906084093
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.51674082704655
