wandb_version: 1

V_P:
  value: 18.623126032320073
V_R:
  value: 16.83725944002155
V_pi_star:
  value: 3.980407025547221
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 658
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2586348985698197
lambda_base:
  value: 0.5010659103141646
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.011490508994156622
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.1479592747958152
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.987300730243556
