wandb_version: 1

V_P:
  value: 17.96182462710823
V_R:
  value: 17.851718616790592
V_pi_star:
  value: 8.60883364305339
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 520
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.16868286973070462
lambda_base:
  value: 0.5637019512225834
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08827254326741624
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.024975104646908
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.093442764299242
