wandb_version: 1

V_P:
  value: 17.89828526444198
V_R:
  value: 18.631527318101952
V_pi_star:
  value: 7.490334790632741
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1495
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2217550219831652
lambda_base:
  value: 0.6265797708528503
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08957041035510067
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.888166402405673
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.480186831667975
