wandb_version: 1

V_P:
  value: 19.136144333528833
V_R:
  value: 18.675472818633267
V_pi_star:
  value: 5.32598288094201
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 627
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.12103212438214309
lambda_base:
  value: 1.2743806305067913
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0761035943416889
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.2965111765017414
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.884727891630352
