wandb_version: 1

V_P:
  value: 18.73199843995384
V_R:
  value: 14.206269763420796
V_pi_star:
  value: 8.598617231675478
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1024
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.29649083990533565
lambda_base:
  value: 0.6164973790868074
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0625901031670158
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.043166072387422
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.74189545187837
