wandb_version: 1

V_P:
  value: 18.75653329194641
V_R:
  value: 15.569689044869742
V_pi_star:
  value: 8.901970118460117
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 694
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2122691570874504
lambda_base:
  value: 1.8632035062665928
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.022777041537386186
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.946675322863403
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.941997783755165
