wandb_version: 1

V_P:
  value: 19.081511805161934
V_R:
  value: 10.582369890237793
V_pi_star:
  value: 9.600186375552788
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1875
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.15248132758644747
lambda_base:
  value: 0.9331594598952054
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08909605993963195
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 2.354863821992985
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.799843611395188
