wandb_version: 1

V_P:
  value: 19.56596929593774
V_R:
  value: 19.136130540471996
V_pi_star:
  value: 6.647298877694736
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 977
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.23483435930202096
lambda_base:
  value: 1.6312105681112763
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0790465067042362
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 4.236813966494346
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 8.49644280405686
