wandb_version: 1

V_P:
  value: 19.363200568668816
V_R:
  value: 19.048244950992736
V_pi_star:
  value: 7.027032640656289
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1017
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.2377280214051262
lambda_base:
  value: 0.9029680821601314
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.0926166284154123
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 1.3113966170756337
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 9.584352940738182
