wandb_version: 1

V_P:
  value: 19.47485325650986
V_R:
  value: 17.527821057051693
V_pi_star:
  value: 8.555584812083046
batch_size:
  value: 64
drift_base_value:
  value: 0.9
drift_magnitude:
  value: 0.27
drift_parameter:
  value: friction
drift_period:
  value: 10000
drift_type:
  value: sine
drift_window_size:
  value: 1569
env_id:
  value: HalfCheetah-v4
gamma:
  value: 0.99
kappa_base:
  value: 0.16796390836060873
lambda_base:
  value: 1.2841979472787388
learning_rate:
  value: 0.0003
max_ent_coef:
  value: 0.08652444065557877
n_envs:
  value: 4
n_steps:
  value: 2048
regularization_sensitivity:
  value: 3.424582671830608
seed:
  value: 42
total_timesteps:
  value: 200000
trust_region_sensitivity:
  value: 7.455919772907032
